refactor: init now uses async await instead of promises
ForestAdmin/forest-express pull request #514
Opened 2020-11-06 09:24 UTC by jeffladiray

## Pull Request checklist:

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

2020-11-06 09:25 UTC, jeffladiray commented on src/index.js
> +function generateAndSendSchema(opts) {
This was just move to a separated function - no code changes here

2020-11-09 09:18 UTC, arnaud-moncel requested changes
Just found a little bug

2020-11-09 09:18 UTC, arnaud-moncel commented on src/index.js
> +    }
As we remove the return we should put a `else if` here ;) 
```suggestion
    if (fs.existsSync(directorySmartImplementation)) {
      await requireAllModels(directorySmartImplementation);
    } else if (opts.configDir) {
      logger.error('The Forest configDir option you configured does not seem to be an existing directory.');
    }
```

2020-11-09 14:17 UTC, arnaud-moncel approved these changes
👌

2020-11-09 14:22 UTC, merged