feat(permissions): handle mutliple permissions cache
ForestAdmin/forest-express pull request #628
Opened 2021-02-04 16:51 UTC by VincentMolinie

## Pull Request checklist:

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

2021-02-04 16:51 UTC, arnaudbesnier commented
Task linked: [CU-d6wd9d Stripe #4 - Add optional global key to PermissionsGetter](https://app.clickup.com/t/d6wd9d)

2021-02-08 10:33 UTC, larcin requested changes

2021-02-08 10:33 UTC, larcin commented on src/services/permissions-getter.js
> +  cleanCache({ storePermissionsInto } = {}) {
[MISC] What does `storePermissionsInto` mean. It makes no sense

2021-02-08 10:33 UTC, larcin commented on src/middlewares/permissions.js
> +        ? this.configStore.lianaOptions.multiplePermissionsCache.getStorePermissionsIntoKey(request)
[MISC] Same here, `getStorePermissionsIntoKey` does not bear that much sense

2021-02-08 10:34 UTC, larcin commented on src/services/permissions-getter.js
> +  cleanCache({ storePermissionsInto } = {}) {
Something like `permissionsCacheKey` or even `environmentId` would be better suited

2021-02-08 17:14 UTC, larcin approved these changes
CC still unhappy

2021-02-10 17:59 UTC, larcin approved these changes

2021-02-11 08:44 UTC, merged